baseurl = "https://www.guermantes.xysz"
title = "Gavin Kelly"
author = "Gavin Kelly"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Ultimate Concerns"

[[menu.main]]
    name = "Home"
    url = "https://www.guermantes.xyz"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/macroscian"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "www.linkedin.com/in/gavin-kelly-7351b4a"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/gavinpaulkelly"
    weight = 4
[[menu.main]]
    name = "Orcid"
    url = "https://orcid.org/0000-0001-7219-560X"
    weight = 5
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 6
